### ISSUE TITLE
Support for List Custom Columns

### ISSUE THREAD

**Issue by christopherhein** [rook/operator-kit#28]
Is this possible with `operator-kit` or with CRDs? I'd like to be able to have a custom output for List to support things like `Status` for example.

```shell
$ kubectl get foo
Name         Kind
Foo          foo.stuff.io
```

**Comment by jbw976** [comment]
I'm not sure if `kubectl` supports custom columns for various resource types such as CRDs.  I have normally done this in the past with the `-o jsonpath` output from kubectl.  For example, this is how I would get the name, status, and container image from all Rook pods:
```
kubectl -n rook-system get pod -o jsonpath='{range .items[*]}{.metadata.name}{"\n\t"}{.status.phase}{"\t"}{.spec.containers[0].image}{"\n"}{end}'
kubectl -n rook get pod -o jsonpath='{range .items[*]}{.metadata.name}{"\n\t"}{.status.phase}{"\t"}{.spec.containers[0].image}{"\n"}{end}
```
The same thing could be done to pick out any specific fields you want from CRDs as well.  I'm not sure if this could be improved on using the `operator-kit` in some way, maybe someone has other ideas.
