### ISSUE TITLE
Support CRD Validation

### ISSUE THREAD

**Issue by christopherhein** [rook/operator-kit#29]
Is CRD validation supported by `operator-kit` if not is that something that is being looked at?

**Comment by jbw976** [comment]
CRD validation is not supported yet within the operator-kit, but that would be a great addition.  I haven't looked very deeply into how CRD validation is done currently, but there are probably some concepts from https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation that could be integrated into the operator-kit to make developers lives easier.  Thanks for this suggestion!
