### ISSUE TITLE
Support Local Kubeconfig

### ISSUE THREAD

**Issue by christopherhein** [rook/operator-kit#30]
Replacing 1.10/1.10 issue with `kubeconfig` for merging

**Comment by jbw976** [comment]
`rook/rook` also uses the operator-kit and is using the kubernetes api/client packages for 1.8.2 also right now.  I haven't seen any issues personally or any reports about that version not working with 1.10 clusters.  We use 1.10 in daily development work and 1.10 is also one of the continuous integration pipelines that we test.
